# To test the image using docker:
# Build the image.
# $ docker build -t webserver:1.0.0 . --file Dockerfile-prod
# List the images.
# $ docker image ls
# To remove an image.
# docker rmi <image-id>
# To start a container.
# docker run -d --name finances -p 8000:8000 webserver
# To list all running containers.
# docker ps
# To stop a running container.
# $ docker stop <container-id>
# To run commands inside an image.
# Alpine images provide the Almquist shell (ash) from BusyBox.
# $ docker exec -it <container-id> ash
# -------------------------------------------------------------------------------------------------
# Use an offical golang image to create the binary.
# Alpine images provide the Almquist shell (ash) from BusyBox.
FROM --platform=arm64 golang:1.22.0-alpine3.19 AS builder

# Create a working directory in the image.
WORKDIR /goapp/

# Copy go.mod and, if present, go.sum from the local machine to the container image.
COPY ./src/go.* ./
# Copy the code from the local machine to the container image.
COPY ./src/main.go ./
COPY ./src/finances ./finances/
COPY ./src/mathutil ./mathutil/
COPY ./src/middlewares ./middlewares/
COPY ./src/misc ./misc/
COPY ./src/security ./security/
COPY ./src/sessions ./sessions/
COPY ./src/s3_storage ./s3_storage/
COPY ./src/webfinances ./webfinances/

# Download necessary Go modules; https://go.dev/ref/mod#go-mod-download
RUN go mod download

# Build the binary; https://go.googlesource.com/sublime-build/+/HEAD/docs/configuration.md
# RUN GOOS="linux" GOARCH="arm64" go build -o ./godir/webserver -v main.go
RUN go build -o ./godir/webserver -v main.go

FROM alpine:3.19

WORKDIR /goapp/

# Same as env = {} in modules.
# ENV HTTP=true
# Set USER to any string to avoid the error:
# user: Current requires cgo or $USER set in environment
# ENV USER="wsf-user"
# ENV HTTP_PORT="8080"

# Copy the binary to the production image from the builder stage.
COPY --from=builder /goapp/godir/ ./
COPY --from=builder /goapp/webfinances/public/ ./webfinances/public/
COPY --from=builder /goapp/webfinances/templates/ ./webfinances/templates/

EXPOSE 8080

USER 1100:1100

# Run the web service on container startup.
ENTRYPOINT ["./webserver"]
