SELECT 'Output from script, run began at: ' AS "Script Information",
  NOW() AS "Date and Time Executed";

-- *******************
-- Create the database
-- *******************
-- Important - You should back up the master database each time that you create, modify, or drop a
-- database.
CREATE DATABASE db_banking_system
WITH
  ALLOW_CONNECTIONS = TRUE
  CONNECTION_LIMIT = -1  -- Unlimited connections.
  ENCODING = 'UTF8'
  LC_COLLATE = 'C.UTF8'  -- Determine the sort order of strings.
  LC_CTYPE = 'C.UTF8'  -- Define character classification rules.
  IS_TEMPLATE = FALSE  -- Only superusers or the database owner can clone the database.
  TEMPLATE = 'template0';

-- Connect to the database.
\c db_banking_system;

-- ******************
-- Create the schemas
-- ******************
CREATE SCHEMA IF NOT EXISTS bs;

-- Once connected, set the search path to look for objects in your schema first, and if not found,
-- to fall back to the default public schema.
SET search_path TO bs, public;

-- *****************
-- Create the tables
-- *****************
-- Customer - Account Relationship
-- One-to-Many Relationship - One customer is allowed to create many accounts.
-- Foreign Key - customer_id in tbl_account is referencing customer_id in tbl_customer.
-- Customer - Customer Info
-- One-to-One Relationship - One customer is allowed to create one customer information.
CREATE TABLE IF NOT EXISTS bs.tbl_customer (
  -- The id column is always generated by the system and users cannot explicitly insert values into
  -- it. See GENERATED BY DEFAULT AS IDENTITY.
  -- A primary key automatically enforces UNIQUE and NOT NULL constraints on the column(s) it's
  -- defined on.
  customer_id          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_type        VARCHAR(16)
                         CHECK(customer_type IN ('regular', 'premium'))
                         DEFAULT 'regular',
  username             VARCHAR(64) UNIQUE NOT NULL,
  password_hash        VARCHAR(256) NOT NULL,
  -- https://www.postgresql.org/docs/current/datatype-datetime.html
  -- This stores date and time along with time zone information. PostgreSQL automatically converts
  -- the timestamp to UTC for storage and adjusts it back based on the current time zone settings
  -- when queried.
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bs.tbl_customer_info (
  customer_info_id  INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Crucially, this foreign key column must also have a UNIQUE constraint applied to it. This
  -- UNIQUE constraint ensures that no two records in the child table (tbl_customer_info) can point
  -- to the same record in the parent table (tbl_customer), thus enforcing the "one-to-one" aspect.
  customer_id       INT UNIQUE NOT NULL,
  first_name        VARCHAR(64) NOT NULL,
  middle_name       VARCHAR(64),
  last_name         VARCHAR(64) NOT NULL,
  date_of_birth     DATE NOT NULL,
  tax_identifier    VARCHAR(16) NOT NULL,
  address_1         VARCHAR(128) NOT NULL,
  address_2         VARCHAR(128),
  city              VARCHAR(128) NOT NULL,
  state             VARCHAR(128) NOT NULL,
  country           VARCHAR(64) NOT NULL,
  zip_code          VARCHAR(32),
  primary_email     VARCHAR(256),
  secondary_email   VARCHAR(256),
  primary_phone     INT NOT NULL,
  secondary_phone   INT,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_customer_info_to_customer
    FOREIGN KEY (customer_id)
    REFERENCES bs.tbl_customer(customer_id)
    -- Automatically deletes all the referencing rows in the child table (tbl_account) when the
    -- referenced rows in the parent table (tbl_customer) are deleted.
    ON DELETE CASCADE
);

-- Account - Transactions Relationship
-- Many-to-Many Relationship - An account can have multiple transactions and a transaction can
--                             involve multiple account numbers.
-- Foreign Key - account_id in tbl_transaction is referencing account_id in tbl_account.
CREATE TABLE IF NOT EXISTS bs.tbl_account (
  account_id      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_id     INT NOT NULL,
  account_number  VARCHAR(32) NOT NULL,
  account_type    VARCHAR(16)
                    CHECK(account_type IN ('savings', 'checking'))
                    DEFAULT 'checking',
  account_status  VARCHAR(16),
                    CHECK(account_status IN ('active', 'closed', 'suspended')),
  balance         NUMERIC(12, 2) NOT NULL,  -- $9,999,999,999.99
  created_at1     DATE NOT NULL,
  closed_at       DATE,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_account_to_customer
    FOREIGN KEY (customer_id)
    REFERENCES bs.tbl_customer(customer_id)
    -- Automatically deletes all the referencing rows in the child table (tbl_account) when the
    -- referenced rows in the parent table (tbl_customer) are deleted.
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bs.tbl_transactions (
  transaction_id    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id        INT NOT NULL,
  transaction_type  VARCHAR(16) NOT NULL
                      CHECK(transaction_type IN ('deposit', 'withdrawal')),
  transaction_date  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  amount            NUMERIC(12, 2) NOT NULL CHECK(amount > 0),
  -- occurance         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_transactions_to_account
    FOREIGN KEY (account_id)
    REFERENCES bs.tbl_account(account_id)
    ON DELETE CASCADE
);

SELECT 'Output from script, run ended at: ' AS "Script Information",
  NOW() AS "Date and Time Executed";
