package webfinances

import (
	"context"
	bank "finance/databases/banking" //Importing a package and assigning it a local alias.
	"finance/renderer"
	admin "finance/webfinances/wfadmin"
	banking "finance/webfinances/wfbanking"
	"fmt"
	"net/http"
	"path/filepath"
	"strings"
	"time"

	"github.com/juan-carlos-trimino/go-logger"
	"github.com/juan-carlos-trimino/go-middlewares"
	"github.com/juan-carlos-trimino/go-sessions"
	sess "github.com/juan-carlos-trimino/go-sessions"
)

var (
  financesMenuPage string = "home"
  contactMenuPage = "contact"
  aboutMenupage string = "about"
)

/***
When handling authentication errors, the application should not disclose which part of the authentication data was incorrect.
Instead of "Invalid username" or "Invalid password", just use "Invalid username and/or password" interchangeably.
***/
func invalidSession(res http.ResponseWriter, correlationId string) {
  logger.LogInfo("Invalid session (webfinances.invalidSession).", correlationId)
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/login.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
      ErrMsg string
    } { "std-wo-headers", "Login", "Invalid username and/or password" },
  })
}

type WfPages struct{}

func (p WfPages) IndexPage(res http.ResponseWriter, req *http.Request) {
  ck := middlewares.MwContextKey{}
  correlationId, _ := ck.GetCorrelationId(req.Context())
  logger.LogInfo("Entering webfinances.IndexPage.", correlationId)
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/index.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
    } { "std-wo-headers", "Welcome to Investments" },
  })
}

func (p WfPages) LoginPage(res http.ResponseWriter, req *http.Request) {
  ck := middlewares.MwContextKey{}
  correlationId, _ := ck.GetCorrelationId(req.Context())
  logger.LogInfo("Entering webfinances.LoginPage.", correlationId)
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/login.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
      ErrMsg string
    } { "std-wo-headers", "Login", "" },
  })
}

func (p WfPages) VerifyLogin(res http.ResponseWriter, req *http.Request) {
  ck := middlewares.MwContextKey{}
  correlationId, _ := ck.GetCorrelationId(req.Context())
  logger.LogInfo("Entering webfinances.VerifyLogin.", correlationId)
  un := req.PostFormValue("uname")
  pw := req.PostFormValue("pwd")
  ok, isAdmin := bank.DbAuthenticateUser(req.Context(), un, pw, correlationId)
  if !ok {
    logger.LogError(fmt.Sprintf("Login failed for user %s.", un), correlationId)
    invalidSession(res, correlationId)
  } else {
    logger.LogInfo(fmt.Sprintf("User %s successfully logged in.", un), correlationId)
    cookie, err := sessions.SetRedis(req.Context(), un)
    /***
    Once a cookie is set on a client, it is sent along with every subsequent request. Cookies store
    historical information (including user login information) on the client's computer. The
    client's browser sends these cookies everytime the user visits the same website, automatically
    completing the login step for the user.

    Sessions, on the other hand, store historical information on the server side. The server uses a
    session id to identify different sessions, and the session id that is generated by the server
    should always be random and unique. You can use cookies or URL arguments to get the client's
    identity.
    ***/
    http.SetCookie(res, cookie)
    tokenString, err := sess.GenerateJwtToken(isAdmin)
    if err != nil {
      logger.LogError(fmt.Sprintf("Error signing token: %v+", err), correlationId)
      http.Error(res, "Internal Server Error", http.StatusInternalServerError)
      return
    }
    adminCookie := sess.CreateCookie("admin_token", tokenString)
    adminCookie.MaxAge = 0  //Zero-value: Omits Max-Age from header.
    adminCookie.Expires = time.Time{}  //Zero-value: Omits Expires from header.
    http.SetCookie(res, adminCookie)
    if isAdmin {
      admin.AddSessionDataPerUser(un, correlationId)
      http.Redirect(res, req, "/admin/welcome", http.StatusSeeOther)
    } else {
      AddSessionDataPerUser(un, correlationId)
      banking.AddSessionDataPerUser(un, correlationId)
      http.Redirect(res, req, "/welcome", http.StatusSeeOther)
    }
  }
}

/***
While it is true that Redis TTL will eventually clean up both keys automatically if the user abandons the app, explicit deletion
on an active logout is a security and resource management necessity for two major reasons:
1. Immediate Invalidation (Security): If you don't call DelRedis, the session key remains valid in Redis until its remaining TTL
   counts down to zero. If a malicious actor intercepted or stole the session_token cookie before logout, they could still make
   valid API requests using that token until the remaining x-minute window closes. Explicitly deleting it closes the window instantly.
2. Instant Memory Cleanup (Optimization): The code deletes a second key: "user:data:" + sessionInfo.UserName. User data hashes or
   structs can be significantly larger than a small session token payload. By purging it the moment a user purposefully clicks
   "Logout," you immediately free up that RAM instead of making Redis hold onto it for an extra x minutes.
***/
func (p WfPages) LogoutPage(res http.ResponseWriter, req *http.Request) {
  ck := middlewares.MwContextKey{}
  correlationId, _ := ck.GetCorrelationId(req.Context())
  logger.LogInfo("Entering webfinances.LogoutPage.", correlationId)
  //The cookie exists because the middleware verified it.
  cookie, _ := req.Cookie("session_token")
  sessionKey := "session:" + strings.Split(cookie.Value, "|")[0]
  //Use context.Background() for terminal network operations to guarantee teardown execution;
  //see the function ValidateSessions in the middleware package for more information.
  bgCtx := context.Background()
  //Delete the session token instantly for explicit security.
  count, err := sessions.DelRedis(bgCtx, sessionKey)
  //Continue with or without error to ensure the client-side cookie is deleted.
  if err != nil {
    logger.LogInfo(fmt.Sprintf("Error deleting the active session id: %v", err), correlationId)
  }
  logger.LogInfo(fmt.Sprintf("%d session(s) deleted.", count), correlationId)
  sessInfo, _ := ck.GetSessionInfo(req.Context())
  //EVICT data from Redis memory; safe because the master copy is in Postgres.
  count, err = sessions.DelRedis(bgCtx, "user:data:" + sessInfo.UserName)
  //Continue with or without error to ensure the client-side cookie is deleted.
  if err != nil {
    logger.LogInfo(fmt.Sprintf("Error deleting user data: %v", err), correlationId)
  }
  logger.LogInfo(fmt.Sprintf("%d user data deleted.", count), correlationId)
  http.SetCookie(res, sess.CreateCookie("session_token", ""))
  http.Redirect(res, req, "/", http.StatusSeeOther)
}

func (p WfPages) WelcomePage(res http.ResponseWriter, req *http.Request) {
  ck := middlewares.MwContextKey{}
  correlationId, _ := ck.GetCorrelationId(req.Context())
  logger.LogInfo("Entering webfinances.WelcomePage.", correlationId)
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/welcome.html",
    "webfinances/templates/title.html",
    "webfinances/templates/datetime.html",
    "webfinances/templates/navbar.html",
    "webfinances/templates/footer.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
      Datetime string
      MenuPage string
    } { "standard", "Investments", logger.DatetimeFormat(), financesMenuPage },
  })
}

func (p WfPages) ContactPage(res http.ResponseWriter, req *http.Request) {
  ck := middlewares.MwContextKey{}
  correlationId, _ := ck.GetCorrelationId(req.Context())
  logger.LogInfo("Entering webfinances.ContactPage.", correlationId)
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/contact.html",
    "webfinances/templates/title.html",
    "webfinances/templates/datetime.html",
    "webfinances/templates/navbar.html",
    "webfinances/templates/footer.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
      Datetime string
      MenuPage string
    } { "standard", "Contact Us", logger.DatetimeFormat(), "contact" },
  })
}

func (p WfPages) AboutPage(res http.ResponseWriter, req *http.Request) {
  ck := middlewares.MwContextKey{}
  correlationId, _ := ck.GetCorrelationId(req.Context())
  logger.LogInfo("Entering webfinances.AboutPage.", correlationId)
  //Explicitly map out the entire structural block stack for this page.
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/about.html",
    "webfinances/templates/title.html",
    "webfinances/templates/datetime.html",
    "webfinances/templates/navbar.html",
    "webfinances/templates/footer.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
      Datetime string
      MenuPage string
    } { "standard", "About Us", logger.DatetimeFormat(), aboutMenupage },
  })
}

func (p WfPages) ServeFinancePages(res http.ResponseWriter, req *http.Request) {
  ck := middlewares.MwContextKey{}
  correlationId, _ := ck.GetCorrelationId(req.Context())
  logger.LogInfo(fmt.Sprintf("Entering webfinances.ServeFinancesPage for path: %s", req.URL.Path), correlationId)
  //Declare dynamic variables based on the URL path.
  var bodyTemplate string
  var pageHeader string
  //Map the incoming route path to its respective template and title.
  switch req.URL.Path {
  case "/fin/ordinaryannuity":
    bodyTemplate = "ordinaryannuity.html"
    pageHeader = "Ordinary Annuity"
  case "/fin/annuitydue":
    bodyTemplate = "annuitydue.html"
    pageHeader = "Annuity Due"
  case "/finances":
    bodyTemplate = "finances.html"
    pageHeader = "Finances"
  case "/fin/simpleinterest":
    bodyTemplate = "simpleinterest.html"
    pageHeader = "Simple Interest"
  default:
    http.NotFound(res, req)
    return
  }
  //Construct the templates slice dynamically using the variables.
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/finances/" + bodyTemplate,  //Dynamically loaded.
    "webfinances/templates/title.html",
    "webfinances/templates/datetime.html",
    "webfinances/templates/navbar.html",
    "webfinances/templates/footer.html",
  }
  //Render using the standard layout data structure.
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct {
      LayoutType string
      Header     string
      Datetime   string
      MenuPage   string
    }{
      "standard",
      pageHeader,  //Dynamically loaded.
      logger.DatetimeFormat(),
      financesMenuPage,
    },
  })
}

func (p WfPages) ServeStaticFiles(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  logger.LogInfo(fmt.Sprintf("Entering webfinances.ServeStaticFiles for path: %s", req.URL.Path), correlationId)
  /***
  Automatically looks at the browser request (e.g., "/public/css/components/base-button.css") and maps it to the
  local file system folder layout.
  ***/
  localPath := filepath.Join("./webfinances", req.URL.Path)
  //Clean the path string to keep it secure.
  localPath = filepath.Clean(localPath)
  //Serve the file dynamically based on the exact path requested.
  http.ServeFile(res, req, localPath)
}
