package webfinances

import (
  bank "finance/databases/banking" //Importing a package and assigning it a local alias.
  "fmt"
  "github.com/juan-carlos-trimino/gplogger"
  "github.com/juan-carlos-trimino/go-middlewares"
  "github.com/juan-carlos-trimino/gpsessions"
  //Package template (html/template) implements data-driven templates for generating HTML output
  //safe against code injection. It provides the same interface as text/template and should be used
  //instead of text/template whenever the output is HTML.
  "html/template"
  "net/http"
  "time"
)

var tmpl *template.Template

/***
In Go, the predefined init() function sets off a piece of code to run before any other part of the
package; i.e., adding the init() function tells the compiler that when the package is imported, it
should run the init() function once. Unlike the main() function that can only be declared once, the
init() function can be declared multiple times throughout a package.
***/
func init() {
  logger.LogInfo("Entering init/webfinances.", "-1")
  /***
  The Must function wraps around the ParseGlob function that returns a pointer to a template and an
  error, and it panics if the error is not nil.
  ***/
  tmpl = template.Must(template.ParseGlob("webfinances/templates/*.html"))
}

/***
When handling authentication errors, the application should not disclose which part of the
authentication data was incorrect. Instead of "Invalid username" or "Invalid password", just use
"Invalid username and/or password" interchangeably.
***/
func invalidSession(res http.ResponseWriter) {
  tmpl.ExecuteTemplate(res, "login_page", struct {
    Error string
  } { "Invalid username and/or password" })
}

type WfPages struct{}

func (p WfPages) IndexPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering IndexPage/webfinances.", correlationId)
  tmpl.ExecuteTemplate(res, "index_page", nil)
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) LoginPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering LoginPage/webfinances.", correlationId)
  tmpl.ExecuteTemplate(res, "login_page", nil)
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) VerifyLogin(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Verifying login credentials.", correlationId)
  un := req.PostFormValue("username")
  pw := req.PostFormValue("password")
  // if !sessions.ValidateUser(un, pw) { //For file.
	if !bank.DbAuthenticateUser(req.Context(), un, pw, correlationId) {
    invalidSession(res)
  } else {
		sessionToken, session := sessions.AddEntryToSessions(un)
    AddSessionDataPerUser(un, correlationId)
    /***
    Once a cookie is set on a client, it is sent along with every subsequent request. Cookies store
    historical information (including user login information) on the client's computer. The
    client's browser sends these cookies everytime the user visits the same website, automatically
    completing the login step for the user.

    Sessions, on the other hand, store historical information on the server side. The server uses a
    session id to identify different sessions, and the session id that is generated by the server
    should always be random and unique. You can use cookies or URL arguments to get the client's
    identity.
    ***/
    http.SetCookie(res, &http.Cookie{
      Name: "session_token",
      Value: sessionToken,
      Expires: session.Expiry,
    })
    http.Redirect(res, req, "/welcome", http.StatusSeeOther)
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) RegisterPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering RegisterPage.", correlationId)
  tmpl.ExecuteTemplate(res, "register_page", nil)
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) LogoutPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering LogoutPage/webfinances.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res)
  } else {
    DeleteSessionDataPerUser(sessions.GetUserName(sessionToken))
    cookie := sessions.DeleteSession(sessionToken)
    http.SetCookie(res, cookie)
    http.Redirect(res, req, "/", http.StatusSeeOther)
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) WelcomePage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering WelcomePage/webfinances.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res)
  } else {
    tmpl.ExecuteTemplate(res, "welcome_page", struct {
      Header string
      Datetime string
    } { "Investments", logger.DatetimeFormat() })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) ContactPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering ContactPage/webfinances.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res)
  } else {
    tmpl.ExecuteTemplate(res, "contact_page", struct {
      Header string
      Datetime string
    } { "Investments", logger.DatetimeFormat() })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) AboutPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering AboutPage/webfinances.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res)
  } else {
    /***
    Executing the template means that we take the content from the template files, combine it with
    data from another source, and generate the final HTML content.
    ***/
    tmpl.ExecuteTemplate(res, "about_page", struct {
      Header string
      Datetime string
    } { "Investments", logger.DatetimeFormat() })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicHomeFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicHomeFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/css/home.css")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicGetParamsFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicGetParamsFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/getParams.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicMortgageFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicMortgageFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/mortgage.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicOaInterestRateFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicOaInterestRateFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/OaInterestRate.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicOaPresentValueFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicOaPresentValueFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/OaPresentValue.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicOaFutureValueFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicOaFutureValueFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/OaFutureValue.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicOaCompoundingPeriodsFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicOaCompoundingPeriodsFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/OaCompoundingPeriods.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicOaEqualPeriodicPaymentsFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicOaEqualPeriodicPaymentsFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/OaEqualPeriodicPayments.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicOaGrowingAnnuityFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicOaGrowingAnnuityFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/OaGrowingAnnuity.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicOaPerpetuityFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicOaPerpetuityFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/OaPerpetuity.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicAdCompoundingPeriodsFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicAdCompoundingPeriodsFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/AdCompoundingPeriods.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicAdEqualPeriodicPaymentsFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicAdEqualPeriodicPaymentsFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/AdEqualPeriodicPayments.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicAdFutureValueFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicAdFutureValueFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/AdFutureValue.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicAdPresentValueFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicAdPresentValueFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/AdPresentValue.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicBondsFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicBondsFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/bonds.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicBondsYTMFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicBondsYTMFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/bondsYTM.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicMiscellaneousFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicMiscellaneousFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/miscellaneous.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicSimpleInterestAccurateFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicSimpleInterestAccurateFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/SimpleInterestAccurate.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicSimpleInterestBankersFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicSimpleInterestBankersFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/SimpleInterestBankers.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) PublicSimpleInterestOrdinaryFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering PublicSimpleInterestOrdinaryFile/webfinances.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/SimpleInterestOrdinary.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) FinancesPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering FinancesPage/webfinances.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res)
  } else {
    tmpl.ExecuteTemplate(res, "finances_page", struct {
      Header string
      Datetime string
    } { "Finances", logger.DatetimeFormat() })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) SimpleInterestPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering SimpleInterestPage/webfinances.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res)
  } else {
    tmpl.ExecuteTemplate(res, "simple_interest_page", struct {
      Header string
      Datetime string
    } { "Simple Interest", logger.DatetimeFormat() })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) OrdinaryAnnuityPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering OrdinaryAnnuityPage/webfinances.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res)
  } else {
    tmpl.ExecuteTemplate(res, "ordinary_annuity_page", struct {
      Header string
      Datetime string
    } { "Ordinary Annuity", logger.DatetimeFormat() })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}

func (p WfPages) AnnuityDuePage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.",
    startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering AnnuityDuePage/webfinances.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res)
  } else {
    tmpl.ExecuteTemplate(res, "annuity_due_page", struct {
      Header string
      Datetime string
    } { "Annuity Due", logger.DatetimeFormat() })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms\n", time.Since(startTime).Microseconds()),
    correlationId)
}
