package webfinances

import (
  bank "finance/databases/banking" //Importing a package and assigning it a local alias.
  banking "finance/webfinances/wfbanking"
  "finance/renderer"
  admin "finance/webfinances/wfadmin"
  "fmt"
  "net/http"
  "path/filepath"
  "time"
  "github.com/juan-carlos-trimino/go-middlewares"
  "github.com/juan-carlos-trimino/gplogger"
  "github.com/juan-carlos-trimino/gpsessions"
)

var financesMenuPage string = "home"
var contactMenuPage = "contact"
var aboutMenupage string = "about"

/***
When handling authentication errors, the application should not disclose which part of the authentication data was incorrect.
Instead of "Invalid username" or "Invalid password", just use "Invalid username and/or password" interchangeably.
***/
func invalidSession(res http.ResponseWriter, correlationId string) {
  logger.LogInfo("Invalid session (webfinances.invalidSession).", correlationId)
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/login.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
      ErrMsg string
    } { "std-wo-headers", "Login", "Invalid username and/or password" },
  })
}

type WfPages struct{}

func (p WfPages) IndexPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.IndexPage.", correlationId)
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/index.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
    } { "std-wo-headers", "Welcome to Investments" },
  })
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) LoginPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering LoginPage.", correlationId)
  templatesNeeded := []string{
    "webfinances/templates/layout.html",
    "webfinances/templates/login.html",
  }
  renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
    Data: struct{
      LayoutType string
      Header string
      ErrMsg string
    } { "std-wo-headers", "Login", "" },
  })
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) VerifyLogin(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering VerifyLogin.", correlationId)
  //Only allow POST requests.
  if req.Method != http.MethodPost {
    logger.LogInfo("Method not allowed.", correlationId)
    http.Error(res, "Method not allowed.", http.StatusMethodNotAllowed)
    return
  }
  un := req.PostFormValue("uname")
  pw := req.PostFormValue("pwd")
  ok, isAdmin := bank.DbAuthenticateUser(req.Context(), un, pw, correlationId)
  if !ok {
    invalidSession(res, correlationId)
  } else {
    sessionToken, session := sessions.AddEntryToSessions(un)
    /***
    Once a cookie is set on a client, it is sent along with every subsequent request. Cookies store
    historical information (including user login information) on the client's computer. The
    client's browser sends these cookies everytime the user visits the same website, automatically
    completing the login step for the user.

    Sessions, on the other hand, store historical information on the server side. The server uses a
    session id to identify different sessions, and the session id that is generated by the server
    should always be random and unique. You can use cookies or URL arguments to get the client's
    identity.
    ***/
    http.SetCookie(res, &http.Cookie{
      Name: "session_token",
      Value: sessionToken,
      Expires: session.Expiry,
    })
    tokenString, err := middlewares.GenerateJwtToken(isAdmin)
    if err != nil {
      logger.LogError(fmt.Sprintf("Error signing token: %v+", err), correlationId)
      http.Error(res, "Error signing token: ", http.StatusInternalServerError)
      return
    }
    http.SetCookie(res, &http.Cookie{
      Name: "admin_token",
      Value: tokenString,
    })
    if isAdmin {
      admin.AddSessionDataPerUser(un, correlationId)
      http.Redirect(res, req, "/admin/welcome", http.StatusSeeOther)
    } else {
      AddSessionDataPerUser(un, correlationId)
      banking.AddSessionDataPerUser(un, correlationId)
      http.Redirect(res, req, "/welcome", http.StatusSeeOther)
    }
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) LogoutPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.LogoutPage.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res, correlationId)
  } else {
    DeleteSessionDataPerUser(sessions.GetUserName(sessionToken))
    cookie := sessions.DeleteSession(sessionToken)
    http.SetCookie(res, cookie)
    http.Redirect(res, req, "/", http.StatusSeeOther)
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) WelcomePage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.WelcomePage.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res, correlationId)
  } else {
    templatesNeeded := []string{
      "webfinances/templates/layout.html",
      "webfinances/templates/welcome.html",
      "webfinances/templates/title.html",
      "webfinances/templates/datetime.html",
      "webfinances/templates/navbar.html",
      "webfinances/templates/footer.html",
    }
    renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
      Data: struct{
        LayoutType string
        Header string
        Datetime string
        MenuPage string
      } { "standard", "Investments", logger.DatetimeFormat(), financesMenuPage },
    })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) ContactPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.ContactPage.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res, correlationId)
  } else {
    templatesNeeded := []string{
      "webfinances/templates/layout.html",
      "webfinances/templates/contact.html",
      "webfinances/templates/title.html",
      "webfinances/templates/datetime.html",
      "webfinances/templates/navbar.html",
      "webfinances/templates/footer.html",
    }
    renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
      Data: struct{
        LayoutType string
        Header string
        Datetime string
        MenuPage string
      } { "standard", "Contact Us", logger.DatetimeFormat(), "contact" },
    })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) AboutPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.AboutPage.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res, correlationId)
  } else {
    //Explicitly map out the entire structural block stack for this page.
    templatesNeeded := []string{
      "webfinances/templates/layout.html",
      "webfinances/templates/about.html",
      "webfinances/templates/title.html",
      "webfinances/templates/datetime.html",
      "webfinances/templates/navbar.html",
      "webfinances/templates/footer.html",
    }
    renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
      Data: struct{
        LayoutType string
        Header string
        Datetime string
        MenuPage string
      } { "standard", "About Us", logger.DatetimeFormat(), aboutMenupage },
    })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) FinancesPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.FinancesPage.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res, correlationId)
  } else {
    templatesNeeded := []string{
      "webfinances/templates/layout.html",
      "webfinances/templates/finances/finances.html",
      "webfinances/templates/title.html",
      "webfinances/templates/datetime.html",
      "webfinances/templates/navbar.html",
      "webfinances/templates/footer.html",
    }
    renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
      Data: struct{
        LayoutType string
        Header string
        Datetime string
        MenuPage string
      } { "standard", "Finances", logger.DatetimeFormat(), financesMenuPage },
    })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) SimpleInterestPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.SimpleInterestPage.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res, correlationId)
  } else {
    templatesNeeded := []string{
      "webfinances/templates/layout.html",
      "webfinances/templates/finances/simpleinterest.html",
      "webfinances/templates/title.html",
      "webfinances/templates/datetime.html",
      "webfinances/templates/navbar.html",
      "webfinances/templates/footer.html",
    }
    renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
      Data: struct{
        LayoutType string
        Header string
        Datetime string
        MenuPage string
      } { "standard", "Simple Interest", logger.DatetimeFormat(), financesMenuPage },
    })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) OrdinaryAnnuityPage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.OrdinaryAnnuityPage.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res, correlationId)
  } else {
    templatesNeeded := []string{
      "webfinances/templates/layout.html",
      "webfinances/templates/finances/ordinaryannuity.html",
      "webfinances/templates/title.html",
      "webfinances/templates/datetime.html",
      "webfinances/templates/navbar.html",
      "webfinances/templates/footer.html",
    }
    renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
      Data: struct{
        LayoutType string
        Header string
        Datetime string
        MenuPage string
      } { "standard", "Ordinary Annuity", logger.DatetimeFormat(), financesMenuPage },
    })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) AnnuityDuePage(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.AnnuityDuePage.", correlationId)
  sessionToken, _ := ctxKey.GetSessionToken(req.Context())
  if sessionToken == "" {
    invalidSession(res, correlationId)
  } else {
    templatesNeeded := []string{
      "webfinances/templates/layout.html",
      "webfinances/templates/finances/annuitydue.html",
      "webfinances/templates/title.html",
      "webfinances/templates/datetime.html",
      "webfinances/templates/navbar.html",
      "webfinances/templates/footer.html",
    }
    renderer.Render(res, "layout", templatesNeeded, renderer.PageData{
      Data: struct{
        LayoutType string
        Header string
        Datetime string
        MenuPage string
      } { "standard", "Annuity Due", logger.DatetimeFormat(), financesMenuPage },
    })
  }
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) PublicHomeFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.PublicHomeFile.", correlationId)
  //Get the absolute path to prevent 404 HTML response (for testing).
  absPath, err := filepath.Abs("./webfinances/public/css/home.css")
  if err != nil {
    logger.LogError("Failed to resolve absolute path", correlationId)
    http.Error(res, "Internal Server Error", http.StatusInternalServerError)
    return
  }
  logger.LogInfo(fmt.Sprintf("Abs path: %s.", absPath), correlationId)
  //Serve using the verified path.
  //http.ServeFile(res, req, absPath)  //Uncomment for testing
  http.ServeFile(res, req, "./webfinances/public/css/home.css")  //Comment for testing
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) PublicSetPageUIFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.PublicSetPageUIFile.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/setPageUI.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) PublicTableStylesheetFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.PublicTableSylesheetFile.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/tableStylesheet.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) PublicTabSplitPageFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.PublicTabSplitPageFile.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/tabSplitPage.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) PublicTabFullPageFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.PublicTabFullPageFile.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/tabFullPage.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}

func (p WfPages) PublicSliderAlphabetFile(res http.ResponseWriter, req *http.Request) {
  ctxKey := middlewares.MwContextKey{}
  correlationId, _ := ctxKey.GetCorrelationId(req.Context())
  startTime, _ := ctxKey.GetStartTime(req.Context())
  logger.LogInfo(fmt.Sprintf("Created correlationId at %s.", startTime.UTC().Format(time.RFC3339Nano)), correlationId)
  logger.LogInfo("Entering webfinances.PublicSliderAlphabetFile.", correlationId)
  http.ServeFile(res, req, "./webfinances/public/js/slider-alphabet.js")
  logger.LogInfo(fmt.Sprintf("Request took %vms", time.Since(startTime).Microseconds()), correlationId)
}
