locals {
  # chomp removes newline characters at the end of a string.
  public_key = chomp(tls_private_key.ssh.public_key_openssh)
}

# The private key generated by this resource will be stored unencrypted in your Terraform state
# file. Use of this resource for production deployments is not recommended.
# https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key
resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits = "4096"
}

resource "local_file" "ssh_private_key" {
  # Private key data in PEM (RFC 1421) format.
  content = tls_private_key.ssh.private_key_pem
  filename = "id_rsa"
  file_permission = "0600"
}

resource "local_file" "ssh_public_key" {
  # The public key data in "Authorized Keys" format. This is not populated for ECDSA with curve
  # P224, as it is not supported.
  # NOTE: The underlying libraries that generate this value append a \n at the end of the PEM.
  content = tls_private_key.ssh.public_key_openssh
  filename = "id_rsa.pub"
  file_permission = "0600"
}
